export type SyntaxKind =
  | "NumberToken"
  | "WhitespaceToken"
  | "PlusToken"
  | "MinusToken"
  | "SlashToken"
  | "StarToken"
  | "PercentToken"
  | "OpenParenthesesToken"
  | "CloseParenthesesToken"
  | "BadToken"
  | "EndOfFileToken"
  | "LiteralExpression"
  | "BinaryExpression"
  | "ParenthesizedExpression";
